### ISSUE TITLE
Client secrets token not works

### ISSUE THREAD

**Issue by salvanicola** [Kuama-IT/kerbero#143]
Nuki client secrets seems to work only with @salvanicola client id and credentials, when retrieving tokens. Call to https://api.nuki.io/oauth/token returns:

`{
    "error": "invalid_client",
    "error_description": "Client authentication failed (e.g., unknown client, no client authentication included, or unsupported authentication method)."
}`

- Is it Nuki support fault? 
- Is the authentication meant to be used only by the owner? (doubt)
- Is the "Testing" status?
- Is an application bug?

**Comment by kuamanet** [comment]
Solved by talking with customer support
